"""add instance_id and ip to gpu table

Revision ID: c8f3859940b6
Revises: 5fe6c071ae5c
Create Date: 2025-09-30 22:16:09.049455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f3859940b6'
down_revision: Union[str, Sequence[str], None] = '5fe6c071ae5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gpus', sa.Column('instance_id', sa.String(length=255), nullable=True))
    op.add_column('gpus', sa.Column('instance_public_ip', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_gpus_instance_id'), 'gpus', ['instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gpus_instance_id'), table_name='gpus')
    op.drop_column('gpus', 'instance_public_ip')
    op.drop_column('gpus', 'instance_id')
    # ### end Alembic commands ###
